export const ONE_PIPELINE_CYCLE_IS_OVER = 'PIPELINE_ONE_CYCLE_IS_OVER';
export const SEND_PIPELINE_RESULT_TO_JSX = 'SEND_PIPELINE_RESULT_TO_JSX';
export const POP_UP_TOAST = 'POP_UP_TOAST';
export const PIPELINE_RUN_OR_STOP = 'PIPELINE_RUN_OR_STOP';