import * as MODULE_MANAGER from "./ModuleInfo";

const NOT_ALLOW_LIST_FD = [
  MODULE_MANAGER.MODULES.FACE_CAMERA,
];

// Canny -> Sobel은 가능
// Sobel -> Canny는 불가능
const NOT_ALLOW_LIST_CANNY = [
  MODULE_MANAGER.MODULES.EDGE_SOBEL,
  MODULE_MANAGER.MODULES.EDGE_PREWITT,
  MODULE_MANAGER.MODULES.EDGE_ROBERTS,
];

const NOT_ALLOW_LIST_HOUGH = [
  MODULE_MANAGER.MODULES.EDGE_SOBEL,
  MODULE_MANAGER.MODULES.EDGE_PREWITT,
  MODULE_MANAGER.MODULES.EDGE_ROBERTS,
];

const NOT_ALLOW_LIST_HOG = [
  MODULE_MANAGER.MODULES.EDGE_SOBEL,
  MODULE_MANAGER.MODULES.EDGE_PREWITT,
  MODULE_MANAGER.MODULES.EDGE_ROBERTS,
];

const NOT_ALLOW_LIST_ROI = [
  MODULE_MANAGER.MODULES.EDGE_HOUGH,
];

const NOT_ALLOW_LIST_FILTER = MODULE_MANAGER.MODULE_LIST[MODULE_MANAGER.GROUPS.FEATURE].concat(
  MODULE_MANAGER.MODULE_LIST[MODULE_MANAGER.GROUPS.AI]
);

const NOT_ALLOW_LIST_DETECTOR = MODULE_MANAGER.MODULE_LIST[MODULE_MANAGER.GROUPS.FEATURE].concat(
  MODULE_MANAGER.MODULE_LIST[MODULE_MANAGER.GROUPS.AI]
);

// const NOT_ALLOW_LIST_FEATURE = MODULE_MANAGER.MODULE_LIST['AI'];

var TABLE = {};
TABLE[MODULE_MANAGER.MODULES.FACE_DETECTOR] = NOT_ALLOW_LIST_FD;
TABLE[MODULE_MANAGER.MODULES.EDGE_CANNY] = NOT_ALLOW_LIST_CANNY;
TABLE[MODULE_MANAGER.MODULES.EDGE_HOUGH] = NOT_ALLOW_LIST_HOUGH;
TABLE[MODULE_MANAGER.MODULES.HOG] = NOT_ALLOW_LIST_HOG;
TABLE[MODULE_MANAGER.MODULES.ROI] = NOT_ALLOW_LIST_ROI;

MODULE_MANAGER.MODULE_LIST[MODULE_MANAGER.GROUPS.FILTER].forEach((module) => {
  if (TABLE[module] !== null) TABLE[module] = NOT_ALLOW_LIST_FILTER.concat(TABLE[module]);
  else TABLE[module] = NOT_ALLOW_LIST_FILTER;
});

// MODULE_MANAGER.MODULE_LIST[MODULE_MANAGER.GROUPS.DETECTOR].forEach((module) => {
//   if (TABLE[module] !== null) TABLE[module] = NOT_ALLOW_LIST_DETECTOR.concat(TABLE[module]);
//   else TABLE[module] = NOT_ALLOW_LIST_DETECTOR;
// });

// MODULE_MANAGER.MODULE_LIST['Feature'].forEach(module => {
//     if (TABLE[module] !== null)
//         TABLE[module] = NOT_ALLOW_LIST_FEATURE.concat(TABLE[module]);
//     else
//         TABLE[module] = NOT_ALLOW_LIST_FEATURE;
// })

export default TABLE;