// Node 
export const ADD_NODE = 'ADD_NODE';
export const REMOVE_NODE = 'REMOVE_NODE';
export const DRAG_NODE = 'DRAG_NODE';
export const CLEAR_LINKBOARD = 'CLEAR_LINKBOARD';

export const SELECT_MODULE = 'SELECT_MODULE';
// export const MODIFY_MODUlE = 'MODIFY_MODUlE';
export const SET_PROPERTIES_OF_NODE = 'SET_PROPERTIES_OF_NODE';
export const SET_CAMERA_OPTIONS = 'SET_CAMERA_OPTIONS';
export const SET_NODE_SIZE = 'SET_NODE_SIZE';

// Link (Path)
export const IS_LINKING = 'IS_LINKING';
export const SET_LINKING_POSITION = 'SET_LINKING_POSITION';
export const ADD_LINK = 'ADD_LINK';
export const REMOVE_LINK = 'REMOVE_LINK';
export const MODIFY_LINK = 'MODIFY_LINK';
export const MODIFY_LINK_BY_NODE_RESIZE = 'MODIFY_LINK_BY_NODE_RESIZE';

// Contextmenu
export const IS_CTXMENU_SHOWING = 'IS_CTXMENU_SHOWING';
export const SET_CTXMENU_POSITION = 'SET_CTXMENU_POSITION';
export const SET_CTXMENU_TYPE = 'SET_CTXMENU_TYPE'

// Property Setting
export const IS_PROPS_SETTING_SHOWING = 'IS_PROPS_SETTING_SHOWING';

// Common
export const SET_TOAST = 'SET_TOAST';

// Pipeline
export const SET_PIPELINE_MANAGER = 'SET_PIPELINE_MANAGER';
export const IS_PIPELINE_RUNNING = 'IS_PIPELINE_RUNNING';
export const SET_NODES = 'SET_NODES';
export const SET_DUMMY_NUMBER = 'SET_DUMMY_NUMBER';
export const IS_PIPELINE_DRAGGING = 'IS_PIPELINE_DRAGGING';

// 20.02.11 Test - File Navigator
export const IS_FILE_NAVIGATOR_SHOWING = 'IS_FILE_NAVIGATOR_SHOWING';
export const IS_PROPERTY_NAVIGATOR_SHOWING = 'IS_PROPERTY_NAVIGATOR_SHOWING';

// 20.03.12 Test - Router
export const SET_CURRENT_MATCH = 'SET_CURRENT_MATCH';